protected/controllers/ChapterController.php
<?php

class ChapterController extends Controller {
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    //public $layout='//layouts/column2';

    /**
     * @return array action filters
     */
    /* public function filters() {
      return array(
      'accessControl', // perform access control for CRUD operations
      );
      } */

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    /* public function accessRules() {
      return array(
      array('allow', // allow all users to perform 'index' and 'view' actions
      'actions' => array('index', 'view'),
      'users' => array('*'),
      ),
      array('allow', // allow authenticated user to perform 'create' and 'update' actions
      'actions' => array('create', 'update'),
      'users' => array('@'),
      ),
      array('allow', // allow admin user to perform 'admin' and 'delete' actions
      'actions' => array('admin', 'delete'),
      'users' => array('admin'),
      ),
      array('deny', // deny all users
      'users' => array('*'),
      ),
      );
      } */

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    /* public function actionView($id) {
      $this->render('view', array(
      'model' => $this->loadModel($id),
      ));
      } */

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        if (app()->user->isAdmin()) {
            $model = new Chapter;
            $user = User::create(array());
            $userChapter = new UserChapter;

            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model, $user);

            if (isset($_POST['Chapter']) && isset($_POST['User'])) {
                //Shared::debug($_POST);
                $model->attributes = $_POST['Chapter'];
                $user->attributes = $_POST['User'];

                $model->validate();
                $user->validate();
                if (!$model->hasErrors() && !$user->hasErrors()) {
                    $model->save(false);
                    $user->save(false);
                    app()->user->setActiveChapter($model->chapter_id);
                    $userChapter = UserChapter::create($user, $model);
                    if ($userChapter != null)
                        $userChapter->save();
                    if (isset($_POST['isAjaxRequest'])) {
                        echo $model->chapter_id;
                        app()->end();
                    }
                } else {
                    // validation errors
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        foreach ($user->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        echo $errors . '</ul>';
                        app()->end();
                    }
                }
            }

            $this->render('create', array(
                'model' => $model,
                'user' => $user,
                'userChapter' => $userChapter
            ));
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {

        $model = $this->loadModel($id);

        if (Auth::hasChapterAccess($model)) {
            app()->user->setActiveChapter($id);
            $user = $model->getContactUser();
            if ($user == null)
                $user = User::create(array());

            // there should be one already anyway
            $userChapter = UserChapter::findByUser($user, $model);
            if ($userChapter == null) {
                //Shared::debug("no contact information");
                $userChapter = new UserChapter;
            }

            $this->performAjaxValidation($model, $user);

            if (isset($_POST['Chapter'])) {
                $model->attributes = $_POST['Chapter'];

                if (isset($_POST['User'])) {
                    //Shared::debug("got user");
                    $user->attributes = $_POST['User'];
                }

                $model->validate();
                $user->validate();

                if (!$model->hasErrors() && !$user->hasErrors()) {

                    $model->save(false);
                    $user->save(false);

                    // just to make sure ... when it wasn't created with chapter
                    if ($userChapter->isNewRecord) {
                        // Shared::debug("creating user vendor");
                        $userChapter = UserChapter::create($user, $model);
                        $userChapter->save();
                    }

                    if (isset($_POST['isAjaxRequest'])) {
                        app()->user->setFlash('success', 'Chapter settings have been saved.');
                        app()->end();
                    } else {
                        $this->redirect(array('dashboard'));
                    }
                } else {
                    // valdiation failed
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        foreach ($user->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        echo $errors . '</ul>';
                        app()->end();
                    }
                }

                /* if ($model->save()) {
                  if (app()->user->isAdmin()) {
                  $this->redirect(url('/chapter'));
                  } else {
                  $this->redirect(url('/chapter/dashboard'));
                  }
                  } */
            }
            $this->render('update', array(
                'model' => $model,
                'user' => $user,
                'userChapter' => $userChapter
            ));
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        if (app()->user->isAdmin()) {
            if (Yii::app()->request->isPostRequest) {

                //To-do: Should we do this? - Also delete users associated with this Chapter.. Vk
                //$chapterUsers = 
                // we only allow deletion via POST request
                $this->loadModel($id)->delete();

                // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
                if (!isset($_GET['ajax']))
                    $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
            }
            else
                throw new CHttpException(400, 'Invalid request. Permission not granted.');
        }else {
            throw new CHttpException(403, 'Access Denied. This operation is for Admins only.');
        }
    }

    /**
     * Lists all models if admin.. if chapter user is logged in, then redirect to their dashboard
     */
    public function actionIndex() {

        $dataProvider = new CActiveDataProvider('Chapter',
                        array(
                            'pagination' => array('pageSize' => 10),
                            'criteria' => array(
                                'condition' => 'entity_id=' . Entity::model()->getEntity(),
                            ),
                ));
        //Shared::debug(app()->user->getActiveChapter());
        $chapter = Chapter::model()->findByPk(app()->user->getActiveChapter());
        if (app()->user->isAdmin()) { //if admin, redirect to Index view to show all chapters
            $id = app()->user->getUser()->user_id;
            $model = User::model()->findByPk($id);
            $this->render('index', array(
                'chapterProvider' => $dataProvider,
                'model' => $model,
                // the user should be redirected to dashbanners if true (after selecting a chapter)
               'dashBanRedirect' => (app()->user->hasFlash('setChapter')?true:false),
            ));
        } else if (Auth::hasChapterAccess($chapter)) { //else if chapter user, redirect to his dashboard
            $this->redirect(url('/chapter/dashboard'));
        } else { // else redirect to Login required
            Yii::app()->user->loginRequired();
        }
    }

    /**
     * Manages all models.
     */
    /* public function actionAdmin() {
      $model = new Chapter('search');
      $model->unsetAttributes();  // clear any default values
      if (isset($_GET['Chapter']))
      $model->attributes = $_GET['Chapter'];

      $this->render('admin', array(
      'model' => $model,
      ));
      } */

    /**

protected/views/chapter/_form.php
<?php

cs()->registerCss('select2-css',
    '#s2id1 {
        width: 100%;
        margin-bottom: 10px;
    }'
    .'.select2-drop-above {
        -webkit-box-shadow: none !important;
        -moz-box-shadow: none !important;
        -o-box-shadow: none !important;
        box-shadow: none !important;
    }'
    .'.select2-container .select2-choice div {
        -webkit-border-radius: 0 3px 3px 0;
        -moz-border-radius: 0 3px 3px 0;
        border-radius: 0 3px 3px 0;
        border-left: 1px solid #ccc;
    }');

$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'chapter-form',
    //'htmlOptions' => array('style' => 'margin-bottom: 0px;'),
    'enableAjaxValidation' => true,
        ));

echo $form->errorSummary($model);

echo $form->textFieldRow($model, 'chapter_name', array('class' => 'span', 'maxlength' => 128));

if (app()->user->isAdmin()) {
    //if (count($model->entity) == 0){
        echo '<div class="form-row" style="width: 100%;">'
            .'<label for="Chapter_entityId" class="required">Entity </label>'
            .'<div class="form-element"><div class="clearfix">';
        $this->widget('ext.select2.ESelect2', array(
            'model' => $model,
            'attribute' => 'entity_id',
            'data' => CHtml::listData(Entity::model()->findAll(), 'entity_id', 'entity_name'),
            'options' => array('placeholder' => 'Select Entity')
        ));
        echo '</div></div></div>';
    //}
}

echo $form->textFieldRow($model, 'ausa_id', array('class' => 'span', 'maxlength' => 16));

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'address', array('class' => 'span')));

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'city', array('class' => 'span', 'maxlength' => 45)));

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'state', array('class' => 'span', 'maxlength' => 45)));

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'zipcode', array('class' => 'span', 'maxlength' => 45)));

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'country', array('class' => 'span', 'maxlength' => 45)));

echo $form->imageFieldRow($model, 'logo', array('class' => 'span', 'maxlength' => 10, 'imageOptions' => array(
    'configuration' => 'logo',
    'layout' => 'logo-layout'
)));

if (app()->user->isAdmin()) {
    echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'offer_app_url', array('class' => 'span', 'maxlength' => 127)));
}

echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->textFieldRow($model, 'chapter_url', array('class' => 'span', 'maxlength' => 127)));


echo CHtml::tag('fieldset', array('class' => 'field-label'), $form->dropDownListRow($model, 'timezone', Shared::$timezones, array('hint' => 'Your offers will have expiration based on this timezone related to GMT')));

// echo $form->textFieldRow($model,'logo',array('class'=>'span5','maxlength'=>10)); 

$this->beginWidget('application.components.widgets.AOPanelFoot');


$this->endWidget();

$this->endWidget();


protected/views/chapter/_members.php
<?php

$this->pageTitle = Yii::app()->name . ' - Chapter Members';
$this->layout = '//layouts/full';
$breadcrumbs = array(
    'breadcrumbs not set'
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));

$columns = array(
    //array('name' => 'vendor_id', 'header' => '#'),
    array('name' => 'ausa_id'),
    array('name' => 'last_name', 'header' => 'Name', 'value' => '$data->getFullName()'),
    array('name' => 'email_address', 'header' => 'Email'),
    array('name' => 'phone_number', 'value' => 'Shared::formatPhone($data->phone_number)'),
    array('name' => 'membership.ausa_product_code'),
    array('name' => 'membership.expiration_date', 'value' => 'Shared::formatShortUSDate($data->membership->expiration_date)')
    //array('name' => 'email_address', 'header' => 'Email'),
);
if (app()->user->isAdmin()) {
    /*$columns[] = array(
        'class' => 'bootstrap.widgets.TbButtonColumn',
        'template' => '{update}{delete}',
    );
     */
} else {
    $columns[] = array('name' => 'member.update', 'header' => '', 'type' => 'raw', 'value' => 'CHtml::link("<button class=\"btn btn-small\"><i class=\"icon-pencil\"></i></button>",url("/member/update/" . $data->member_id))', 'htmlOptions' => array('width' => '20', 'class' => 'status-center'));
}

$dataArray = array(
        'type' => 'striped bordered condensed',
        'filter' => $member,
        'dataProvider' => $member->search(),
        //'template'=>"{items}",
        'columns' => $columns,
    );

if(app()->user->hasFlash('success')) {
    cs()->registerScript('updates','setTimeout(function() { showSuccess(\''.app()->user->getFlash('success').'\'); }, 500);');
}
?>

<div class="ausa-contentMain row-fluid">
    <?php
    $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false));
    $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons marker', 'panelTitle' => 'Chapter Members'));
        $this->widget('ausa.widgets.AOButtonGroup', array(
            'type'=>'',
            'htmlOptions' => array('style' => 'color: red'),
            'buttons'=>array(
                array('icon'=>'cog', 'items'=>array(
                    array('label'=>'Add a Member', 'icon' => 'plus', 'url'=>url('/member/create')),
                    array('label'=>'Upload Members', 'icon' => 'circle-arrow-up', 'url'=>url('/member/upload')),
                    '---',
                    array('label'=>'Get Help', 'icon' => 'question-sign', 'url' => '#'),
                )),
            ),
        ));
    $this->endWidget();

    $this->widget('bootstrap.widgets.TbGridView', $dataArray);

$this->endWidget();
?>

protected/views/chapter/_vendors.php
<?php
$this->pageTitle = Yii::app()->name . ' - Chapter Vendors';
$this->layout = '//layouts/full';
$breadcrumbs = array(
    'breadcrumbs not set'
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs, 'map' => true));

$branchArray = Chapter::model()->getVendorBranches($model->chapter_id);

/*cs()->registerScriptFile('https://maps-api-ssl.google.com/maps/api/js?v=3&sensor=false');
cs()->registerScript('chapterVendorMap',
        'function initialize() {'
            .'var mapOptions = {'
                .'center: new google.maps.LatLng(31.771375,-106.487148),'
                .'zoom: 13,'
                .'mapTypeId: google.maps.MapTypeId.ROADMAP,'
                .'overviewMapControl: true,'
                .'overviewMapControlOptions: { opened: false, },'
                .'scrollwheel: false,'
                .'scaleControl: true,'
                .'zoomControlOptions: {'
                    .'style: google.maps.ZoomControlStyle.LARGE,'
                    .'position: google.maps.ControlPosition.LEFT_TOP'
                .'},'
                .'mapTypeControl: true,'
                .'mapTypeControlOptions: {'
                    .'style: google.maps.MapTypeControlStyle.DROPDOWN_MENU'
                .'},'
            .'};'
            .'var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);'
            .'var geocoder = new google.maps.Geocoder();'
        .'}'
        .'initialize();');
*/

$columns = array(
    //array('name' => 'vendor.vendor_id'),
    array('name' => 'vendor.vendor_name', 'header' => 'Name'),
    array('name' => 'salesTeam', 'header' => 'Sales Team', 'value' => 'VendorMembership::model()->getVendorsSalesteam($data->vendor->vendor_id)'),
    //array('name' => 'vendor.address', 'header' => 'Address'),
    array('name' => 'vendor.industry', 'header' => 'Industry', 'value' => '$data->vendor->category->category_name'), //Chapter::model()->getIndustryName($data->vendor->industry)
    array('name' => 'since', 'header' => 'Date Joined', 'type' => 'raw', 'value' => 'Shared::formatShortUSDate($data->since)'),
    array('name' => 'vendor.expiration', 'header' => 'Expires', 'type' => 'raw', 'value' => 'Shared::formatShortUSDate($data->vendor->expiration)'),
        //array('name' => 'vendor.st_name', 'header' => 'Sales Team'),
        /*array(
          'class' => 'bootstrap.widgets.TbButtonColumn',
          'template' => '{update}',
          ), */
);
$dataArray = array(
    'type' => 'striped bordered condensed',
    'dataProvider' => $dataProvider,
    //'template'=>"{items}",
    'columns' => $columns
);
?>

<div class="ausa-contentMain row-fluid">
    <?php
    $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false));
    $this->widget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'Vendors in ' . $chapterName));
    $this->widget('bootstrap.widgets.TbGridView', $dataArray);
    $this->endWidget();
    ?>

protected/views/chapter/create.php
<?php
$this->layout = '//layouts/full';
$breadcrumbs = array(
    'breadcrumbs not set'
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));
?>

<?php
    $this->beginWidget('application.components.widgets.AOStickyBar', array('sticky' => true, 'panelWrap' => true));
        $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType' => 'link',
            'icon' => 'remove white',
            'type' => 'danger',
            'url' => url('/site/index'),
            'label' => 'Cancel',
            'htmlOptions' => array('style' => 'margin: 5px 25px 0px 8px; float: right',)
        ));
        $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType' => 'ajaxSubmit',
            'type' => 'success',
            'url' => url('/chapter/create'),
            'htmlOptions' => array(
                'style' => 'margin: 5px 8px; float: right',
                'id' => 'save-chapter-button',
            ),
            'loadingText' => 'processing...',
            'ajaxOptions' => array(
                'data' => 'js:serializeAll()+"&isAjaxRequest=1"',
                'beforeSend' => 'function(){$("#save-chapter-button").button("loading")}',
                'success' => 'function(response){

                    if (response.length < 5){
                        // saved, lets go one step further
                        window.location.href="' . url('chapter/update') . '/" + response;
                    }else{
                        console.log(response);
                        $("#save-chapter-button").button("reset");

                        // we are going to display error message
                        $("#ajax-errors-holder").show();
                        $("#ajax-errors").html(response);
                        showError(\'Could not save the chapter. Please check the error fields below.\');
                    }
                }',
            ),
            'icon' => 'ok white',
            'label' => 'Save',
        ));
    $this->endWidget(); ?>

<div style="width: 100%; margin-bottom: 25px; position: relative; float: left; display: none;" id="ajax-errors-holder">
    <?php
    $this->widget('application.components.widgets.AONotice', array('notice' => '<div id="ajax-errors"></div>', 'noticeType' => 'errors'));
    ?>
</div>

    <?php
// Basic company information
    $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => true));
    $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'Chapter Information'));
    $this->endWidget();
    echo $this->renderPartial('_form', array('model' => $model));
    $this->endWidget();

// User contact form
    $this->beginWidget('application.components.widgets.AOPanel');
    $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons download_to_computer', 'panelTitle' => 'Contact Person'));
    $this->endWidget();
    echo $this->renderPartial('//user/_contact_form', array('model' => $user, 'userChapter' => $userChapter));
    $this->endWidget();
    ?>

protected/views/chapter/index.php
<?php

$this->layout = '//layouts/full';
$breadcrumbs = array(
    'My Dashboard' => app()->user->getHomeUrl(),
    'Chapters'
);

if(app()->user->hasFlash('setChapter')) {
    cs()->registerScript('updates','setTimeout(function() { showError(\''.app()->user->getFlash('setChapter').'\'); }, 500);');
}

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));
?>

    <?php $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false)); ?>
    <?php $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'AUSA Chapters')); ?>
    <?php
    $this->widget('ausa.widgets.AOButtonGroup', array(
        'type' => '',
        'buttons' => array(
            array('icon' => 'cog', 'items' => array(
                    array('label' => 'Add Chapter', 'icon' => 'plus', 'url' => url('chapter/create')),
                    '---',
                    array('label' => 'Get Help', 'icon' => 'question-sign', 'url' => '#'),
            )),
        ),
    ));

    $this->endWidget();

    if($dashBanRedirect == false){
        $chapterClick = array('name' => 'chapter_name', 'header' => 'Chapter Name', 'type' => 'raw', 'value' => 'CHtml::link($data->chapter_name,url("/chapter/go/" . $data->chapter_id))');
    } else {
        $chapterClick = array('name' => 'chapter_name', 'header' => 'Chapter Name', 'type' => 'raw', 'value' => 'CHtml::link($data->chapter_name,"?",array(\'submit\' => url("/dashBanner/"),\'params\' => array(\'postChapter\' => $data->chapter_id)))');
    }

    $dataArray=array(
        'type' => 'striped bordered condensed',
        'dataProvider' => $chapterProvider,
        'columns' => array(
            $chapterClick,
            array('name' => 'ausa_id', 'header' => 'AUSA ID'),
            array('name' => 'city', 'header' => 'City'),
            array('name' => 'state', 'header' => 'State'),
        ),
    );
    
    
    if (app()->user->isAdmin()) {
        $dataArray['columns'][] = array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{update} {delete}',
        );
    }
    
    $this->widget('bootstrap.widgets.TbGridView', $dataArray);
    ?>

    <?php $this->endWidget(); ?>

protected/views/chapter/update.php
<?php

$this->pageTitle = Yii::app()->name . ' - Chapter Update';
$this->layout = '//layouts/full';
$breadcrumbs = array(
    'breadcrumbs not set'
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));

$this->widget('application.components.widgets.AOGrid');
?>

    <?php
    $this->beginWidget('application.components.widgets.AOStickyBar', array('sticky' => true, 'panelWrap' => true));
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'link',
        'icon' => 'remove white',
        'type' => 'danger',
        'url' => url('/chapter/dashboard'),
        'label' => 'Cancel',
        'htmlOptions' => array('class' => 'pull-right', 'style' => 'margin: 5px 25px 0px 8px',)
    ));
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'ajaxSubmit',
        'type' => 'success',
        'url' => url('/chapter/update/' . $model->chapter_id),
        'htmlOptions' => array(
            'style' => 'margin: 5px 8px; float: right',
            'id' => 'save-chapter-button',
        ),
        'loadingText' => 'processing...',
        'ajaxOptions' => array(
            'data' => 'js:serializeAll()+"&isAjaxRequest=1"',
            'beforeSend' => 'function(){$("#save-chapter-button").button("loading")}',
            'success' => 'function(response){

                        if (response.length < 5){
                            // saved, lets go one step further
                            window.location.href="' . url('chapter/dashboard') . '";
                        }else{
                            console.log(response);
                            $("#save-chapter-button").button("reset");

                            // we are going to display error message
                            $("#ajax-errors-holder").show();
                            $("#ajax-errors").html(response);
                            showError(\'Could not save the chapter. Please check the error fields below.\');
                        }
                    }',
        ),
        'icon' => 'ok white',
        'label' => 'Save',
    ));
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'ajaxSubmit',
        'type' => '',
        'url' => url('/chapter/update/' . $model->chapter_id),
        'htmlOptions' => array(
            'style' => 'margin: 5px 8px; float: right',
            'id' => 'apply-chapter-button',
        ),
        'loadingText' => 'processing...',
        'ajaxOptions' => array(
            'data' => 'js:serializeAll()+"&isAjaxRequest=1"',
            'beforeSend' => 'function(){$("#apply-chapter-button").button("loading")}',
            'success' => 'function(response){
                        $("#apply-chapter-button").button("reset");
                        if (response.length < 5){
                            showSuccess(\'Chapter Settings have been updated.\');
                            $("#ajax-errors-holder").hide();
                        }else{
                            showError(\'Could not save the chapter. Please check the error fields below.\');
                            $("#ajax-errors-holder").show();
                            $("#ajax-errors").html(response);
                            $(".notification").css({\'display\':\'block\', \'opacity\':\'1\'});
                        }
                    }',
        ),
        'icon' => 'ok',
        'label' => 'Apply',
    ));
    $this->endWidget();
    ?>

<div style="width: 100%; margin-bottom: 25px; position: relative; float: left; display: none;" id="ajax-errors-holder">
    <?php $this->widget('application.components.widgets.AONotice', array('notice' => '<div id="ajax-errors"></div>', 'noticeType' => 'errors')); ?>
</div>

<div class="ausa-contentMain row-fluid">
    <div id="ausa-contentMainTiles">
        <ul id="tiles">
            <li class="grid">
                <?php
                // Basic company information
                $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => true));
                    $this->widget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'Chapter Information'));
                    echo $this->renderPartial('_form', array('model' => $model));
                $this->endWidget();
                ?>
            </li>
            <li class="grid">
                <?php
                // User contact form
                $this->beginWidget('application.components.widgets.AOPanel');
                    $this->widget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons download_to_computer', 'panelTitle' => 'Contact Person'));
                    echo $this->renderPartial('//user/_contact_form', array('model' => $user, 'userChapter' => $userChapter));
                $this->endWidget();
                ?>
            </li>
        </ul>
    </div>