protected/models/Banner.php
<?php

/**
 * This is the model class for table "banner".
 *
 * The followings are the available columns in table 'banner':
 * @property string $banner_id
 * @property string $vendor_id
 * @property string $start_date
 * @property string $end_date
 * @property string $updated_on
 * @property string $banner_name
 * @property integer $active
 * @property integer $dashobard Whether or not the banner is displayed on the mobile dashboard
 * @property integer $published
 * @property string $layout
 * @property string $icon_image
 * @property string $panorama_image
 * @property string $message_text
 * @property string $target
 * @property string $external_url
 * @property integer $impressions
 * @property integer $clicks
 *
 * The followings are the available model relations:
 * @property Vendor $vendor
 */
class Banner extends AOActiveRecord {

    /**
     * Virtual attribute used in a form
     * @var type 
     */
    public $campaign_duration;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Banner the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'banner';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('vendor_id, banner_name, layout, target, panorama_image', 'required'),
            array('active, published, impressions, clicks, dashboard', 'numerical', 'integerOnly' => true),
            array('vendor_id, offer_id', 'length', 'max' => 10),
            array('banner_name', 'length', 'max' => 63),
            array('layout', 'length', 'max' => 5),
            array('icon_image, panorama_image', 'length', 'max' => 31),
            array('start_date', 'validateConcurency'),
            array('start_date, end_date', 'required', 'on' => 'publish'),
            array('start_date', 'validateConcurency', 'on' => 'publish', 'publishedOnly' => true), // when the banner is being published, we need to make sure there is only one
            array('message_text, external_url', 'length', 'max' => 255),
            array('target', 'length', 'max' => 8),
            array('start_date, end_date, updated_on', 'safe'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('banner_id, vendor_id, start_date, end_date, updated_on, banner_name, active, published, layout, icon_image, panorama_image, message_text, target, external_url, impressions, clicks', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
        );
    }

    public function scopes() {
        return array(
            // only those, which should be sent to cellphones
            'published' => array(
                'condition' => 'published=1 AND vendor.disabled=0 AND vendor.banner_expiration > NOW()',
                'with' => 'vendor',
            )
        );
    }

    public function behaviors() {
        return array(
            'offerBehavior' =>
            array(
                'class' => 'application.models.behaviors.OfferBehavior'
            )
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'banner_id' => 'Banner',
            'vendor_id' => 'Vendor',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'updated_on' => 'Updated On',
            'banner_name' => 'Banner Name',
            'active' => 'Active',
            'published' => 'Published',
            'layout' => 'Layout',
            'icon_image' => 'Icon Image',
            'panorama_image' => 'Panorama Image',
            'message_text' => 'Message Text',
            'target' => 'Target',
            'external_url' => 'External Url',
            'impressions' => 'Impressions',
            'clicks' => 'Clicks',
        );
    }

    /**
     * We need to make sure that no other banners are in the same window
     * We want warning for unpublished banners and error for published
     * @param type $attribute
     * @param type $params
     */
    function validateConcurency($attribute, $params) {
        // the question is how to produce warning on ajax validate and error on
        // published resource
        $checkPublished = false;
        if (isset($params['publishedOnly'])) {
            $checkPublished = $params['publishedOnly'];
        }
        if ($this->published && $checkPublished && $this->vendor_id) {
            // find coliding banners using interval arithmetics
            $colliding = Banner::model()->findAllBySql("SELECT banner_id, banner_name, start_date, end_date, published FROM banner 
                WHERE vendor_id={$this->vendor_id} AND published > 0 " . ($this->isNewRecord ? '' : ' AND banner_id != ' . $this->banner_id) . " AND(
                (start_date<='{$this->start_date}' AND end_date >= '{$this->start_date}') OR
                (start_date<='{$this->end_date}' AND end_date >='{$this->end_date}') OR
                (start_date>='{$this->start_date}' AND end_date <='{$this->end_date}'))");
            $allowed = $this->vendor->max_banners;
            if ($allowed == 0) {
                $this->addError('banner_name', 'Your account is not enabled to publish a banner. Please contact your sales person.');
                return false;
            } else if (count($colliding)) {
                Shared::debug("there are some colliding banners");
                // we don't really care about expiration date right now
                if (count($colliding) >= $allowed) {
                    // allright, this would not work
                    // get list of banners, so we can display nice error message
                    $existingMsg = '';
                    foreach ($colliding as $banner) {
                        $existingMsg .= ', ' . $banner->banner_name . ' (from ' . Shared::formatDateLonger($banner->start_date) . ' to ' . Shared::formatDateLonger($banner->end_date) . ')';
                    }

                    $this->addError('start_date', 'Please select different publishing date for this banner. Published banners: ' . substr($existingMsg, 2));
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * Constructs default values before the model is displayed in the create form
     */
    public function loadDefaults() {
        if (!$this->start_date) {
            $this->start_date = date('Y-m-d', time());
        }

        if (!$this->end_date) {
            $this->end_date = Shared::toDatabase(strtotime($this->start_date . " +12 month"));
        }

        if (!$this->target) {
            $this->target = 'external';
        }

        if (!$this->layout) {
            $this->layout = 'image';
        }

        $vendor = Vendor::model()->findByPk(app()->user->getActiveVendor());

        if (!$this->external_url) {
            $this->external_url = $vendor->website;
        }

        if (!$this->banner_name) {

            $this->banner_name = "Banner #" . (count($vendor->banners) + 1);
            Shared::debug($this->banner_name);
        }
    }

    /**
     * Create or update the model from form. This function does not save or
     * valiate the model.
     * @param type $input
     * @return boolean|Offer
     */
    public static function create($input, $model = null) {
        // suppose the model is alrady found in the database
        Shared::debug("create");
        if ($model == null) {
            $model = self::createModel('Banner', $input);
        } else {
            $model->setAttributes($input);
        }

        // set basic attributes
        $vendor = Yii::app()->user->getActiveVendor();
        if (!$model->vendor_id && !$vendor) {
            return null;
        }

        if (!$model->vendor_id)
            $model->vendor_id = $vendor;
        $model->updated_on = Shared::timeNow();

        // calculate the end date
        if ($model->dashboard != 1) {

            if (!isset($input['campaign_duration']) && isset($input['end_date'])) {
                // use end date from the select
                $model->end_date = $input['end_date'];
                if (strtotime($model->end_date) < strtotime($model->start_date)) {
                    // set default duration
                    $model->end_date = Shared::toDatabase(strtotime($model->start_date . " +12 month"));
                }
            } else if (isset($input['campaign_duration'])) {
                // calculate the end date
                $duration = $input['campaign_duration'];
                if ($duration < 1 || $duration > 12) {
                    $duration = 1;
                }
                if (isset($input['start_date']) && $model->isNewRecord) {
                    $model->end_date = Shared::toDatabase(strtotime($model->start_date . " +" . $duration . " month"));
                } else {

protected/controllers/BannerController.php
<?php

class BannerController extends Controller {

    public $layout = '//layouts/full';

    /**
     * List of active / expired banners visible for the vendor.
     * Display warning page when the vendor does not have banners active.
     */
    public function actionIndex() {
        $vendor = app()->user->getActiveVendor();
        $setVendor = app()->request->getParam('postBannerVendor');
        if ($vendor) {
            $model = Vendor::model()->findByPk($vendor);
            if ($model->isBannerEnabled()) {
                $dataProvider = new CActiveDataProvider('Banner', array(
                            'criteria' => array(
                                'condition' => 'vendor_id=' . $vendor . ' AND dashboard != 1',
                            ),
                        ));
                $this->render('index', array('vendor' => $model, 'dataProvider' => $dataProvider));
            } else {
                $this->render('disabled', array('vendor' => $model));
            }
        } elseif($setVendor) {
            $vendor = Vendor::model()->findByPk($setVendor);
            if (Auth::hasVendorAccess($vendor)) {
                app()->user->setActiveVendor($setVendor);
                $this->redirect(url('/banner'));
            }
        } else {
            app()->user->loginRequired(true,false,true);
        }
    }

    public function actionCreate() {

        $model = new Banner;
        $model->loadDefaults();

        $vendor = Vendor::model()->findByPk(app()->user->getActiveVendor());
        Shared::debug($vendor);
        if ($vendor != null && $vendor->isBannerEnabled()) {

            $this->performAjaxValidation($model);
            Shared::debug($_POST);
            if (isset($_POST['Banner'])) {
                Shared::debug($_POST);
                $model = Banner::create($_POST['Banner'], $model);

                if ($model->save()) {
                    if (isset($_POST['isAjaxRequest'])) {
                        echo $model->banner_id;
                        app()->end();
                    } else {
                        $this->redirect(array('/banner/update' . $model->banner_id));
                    }
                } else {
                    // validation issue
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }

                        echo $errors . '</ul>';
                        app()->end();
                    }
                }
            }

            $this->render('create', array(
                'model' => $model,
                'vendor' => $vendor));
        } else {
            app()->user->loginRequired();
        }
    }
    
    public function actionUpdate($id) {

        Shared::debug($id, 'banner_id');
        $model = Banner::model()->findByPk($id);

        if (Auth::hasVendorAccess($model)) {
            $vendor = $model->vendor;
            if (!$vendor->isBannerEnabled() || $model->dashboard == 1){
                $this->render('disabled', array('vendor' => $vendor));
            }
            
            $this->performAjaxValidation($model);
            Shared::debug($_POST);
            if (isset($_POST['Banner'])) {
                Shared::debug($_POST);
                $model = Banner::create($_POST['Banner'], $model);

                if ($model->save()) {
                    if (isset($_POST['isAjaxRequest'])) {
                        echo $model->banner_id;
                        app()->end();
                    } else {
                        $this->redirect(array('/banner/update' . $model->offer_id));
                    }
                } else {
                    // validation issue
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }

                        echo $errors . '</ul>';
                        app()->end();
                    }
                }
            }

            $this->render('update', array(
                'model' => $model,
                'vendor' => $vendor));
        } else {
            app()->user->loginRequired();
        }
    }

    public function actionGetPublishingInfo($bannerId, $startDate, $endDate){
        $model = Banner::model()->findByPk($bannerId);
        if (Auth::hasVendorAccess($model)){
            echo json_encode($model->getPublishingInfo(CHtml::decode($startDate), CHtml::decode($endDate)));
        } else{
            throw new CHttpException(403, 'Access Denied.');
        }
    }
    
    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model) {
        Shared::debug($_POST);
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'banner-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/banner/_banner_form.php
<?php

$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'offer-form',
    //'htmlOptions' => array('style' => 'margin-bottom: 0px;'),
    'enableAjaxValidation' => false,
        ));

echo $form->errorSummary($model);

echo $form->imageFieldRow($model, 'panorama_image', array(
    'class' => 'span',
    'imageOptions' => array(
        'configuration' => 'banner',
        'layout' => 'banner-layout',
        'noPhoto' => url('/images/banner.png'),
        'afterFinish' => '
console.log(response);
var timestamp = new Date().getTime();            
$("#phone-preview").css("background-image", "url(" + response["fullUrl"] + "?w=320&h=50&v=" + timestamp + ")");'
        )));

$this->beginWidget('application.components.widgets.AOPanelFoot');

$this->endWidget();

$this->endWidget();
?>

protected/views/banner/_campaign_form.php
<?php

$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'offer-form',
    //'htmlOptions' => array('style' => 'margin-bottom: 0px;'),
    'enableAjaxValidation' => false,
        ));

echo "<div id='publishing-info' class='ausa-form-info'>";
// info about available dates
echo "</div>";

echo $form->errorSummary($model);

echo $form->textFieldRow($model, 'banner_name', array('class' => 'span', 'maxlength' => 12, 'hint' => 'This is internal name. This will not be shown to users of the app.'));

echo $form->datepickerRow($model, 'start_date', array('class' => 'span', 'hint' => 'What date would you like this banner to be published?'));

$info = $model->getPublishingInfo();
$displayDuration = true;
// is there a custom end date??
$startDay = date('d', Shared::toTimestamp($model->start_date));
$endDay = date('d', Shared::toTimestamp($model->end_date));

if ($startDay != $endDay) {
    $displayDuration = false;
}

// get the default value for duration
$months = 1;
if (strlen($model->end_date)) {
    $diff = strtotime($model->end_date) - strtotime($model->start_date);
    $months = ceil($diff / Shared::month);
}

$minMonth = 1;

if ($model->published) {
    // we might restrict the number of months. Make it no less than one
    // and do not go below the current month
    $diff = strtotime($model->end_date) - time();
    if ($diff > 0) {
        $minMonth = ceil($diff / Shared::month);
    }
}

$monthsArr = array();
for ($i = $minMonth; $i <= 12; $i++) {
    if ($i == 1) {
        $monthsArr[$i] = "1 Month";
    } else {
        $monthsArr[$i] = $i . " Months";
    }
}

if ($displayDuration) {
    echo $form->customRow($model, 'end_date', 'Publish for', CHtml::dropDownList('Banner[campaign_duration]', $months, $monthsArr) . "&nbsp;&nbsp;<span class='ajax-link' id='calendar-switch'>or select end date</span>", array('class' => 'span', 'id' => 'publish-for'));
}

// by default hidden end_date select
echo "<div id='end-date' " . ($displayDuration ? "style='display: none;" : '') . "'>";
echo $form->datepickerRow($model, 'end_date', array('class' => 'span', 'hint' => 'Last day your banner is going to be published.'));
echo "</div>";




/*
  if (!$model->isNewRecord) {
  if ($model->published == 0) {

  $button = $this->widget('bootstrap.widgets.TbButtonGroup', array(
  'type' => 'primary',
  'toggle' => 'radio', // 'checkbox' or 'radio'
  'buttons' => array(
  array('label' => 'Not yet', 'active' => true),
  array('label' => 'Publish the banner', 'type' => 'success', 'htmlOptions' => array('id' => 'publish-button')),
  ),
  ), true);
  echo $form->customRow($model, 'published', 'Publishing', $button, array('hint' => 'Upon Publish, this banner is ready to be displayed on the mobile app from the Start Date.'));
  echo CHtml::activeHiddenField($model, 'published');

  cs()->registerScript('publish-button', '
  $("#publish-button").click(function(){
  if ($(this).hasClass("active")){
  $("#Banner_published").val(0);
  }else{
  $("#Banner_published").val(1);
  }
  });
  ');
  } else {
  echo $form->customRow($model, 'published', 'Published', 'The banner is <b>published</b>.', array('hint' => 'Upon Publish, this banner is ready to be displayed on the mobile app from the Start Date.'));
  }
  } */

if (!$model->isNewRecord) {
    //if ($model->published == 0) {

    $button = $this->widget('bootstrap.widgets.TbButtonGroup', array(
        'type' => 'primary',
        'toggle' => 'radio', // 'checkbox' or 'radio'
        'buttons' => array(
            array('label' => 'Not yet', 'active' => !$model->published),
            array('label' => 'Publish the banner', 'active' => $model->published, 'type' => 'success', 'htmlOptions' => array('id' => 'publish-button')),
        ),
            ), true);
    if ($model->published) {
        $button = $this->widget('bootstrap.widgets.TbButton', array(
            'type' => 'danger',
            'toggle' => true, // 'checkbox' or 'radio'
            'label' => 'Unpublish',
            'size' => 'small',
            'htmlOptions' => array('id' => 'unpublish-button')
                ), true);
        $element = 'The banner is <b>published</b>. ' . $button;
    } else {
        $button = $this->widget('bootstrap.widgets.TbButton', array(
            'type' => 'success',
            'toggle' => true, // 'checkbox' or 'radio'
            'label' => 'Publish',
            'size' => 'small',
            'htmlOptions' => array('id' => 'publish-button')
                ), true);
        $element = 'The banner is <b>unpublished</b>. ' . $button;
    }
    echo $form->customRow($model, 'published', 'Publishing', $element, array('hint' => 'Publish the banner to display in our cellphone app.'));
    echo CHtml::activeHiddenField($model, 'published');

    cs()->registerScript('publish-button', '
            $("#publish-button").click(function(){
                if ($(this).hasClass("active")){
                    $("#Banner_published").val(0);
                }else{
                    $("#Banner_published").val(1);
                }
            });
            $("#unpublish-button").click(function(){
                if ($(this).hasClass("active")){
                    $("#Banner_published").val(1);
                }else{
                    $("#Banner_published").val(0);
                }
            });
        ');
} else {
    echo $form->customRow($model, 'published', 'Publishing', 'Save the banner first to see the publishing options.', array('hint' => 'Publish the banner to display it in our cellphone app.'));
}

cs()->registerScript('publish-banner-for', '
            // Update end date in the end date calendar together with drop box month select 
            $("#Banner_campaign_duration").change(function(){
                var months = $("#Banner_campaign_duration option:selected").val();
                
                // possible problem with date formatting on safari
                // stores array of (Y,M,D)
                var dateParts = $("#Banner_start_date").val().split("-");
                
                if (dateParts[1] + months > 12){
                    dateParts[0]++;
                    dateParts[1] -= 12;
                }
                
                dateParts[1] += months;

                var startDate = new Date(dateParts[0], dateParts[1] - 1, dateParts[2]);
        
                var endDate = startDate.getFullYear() + "-";
                endDate += (startDate.getMonth() + 1) + "-";
                endDate += startDate.getDate();
                $("#Banner_end_date").val(endDate);
            });

            $("#calendar-switch").click(function(){
                $("#publish-for").hide();
                $("#end-date").show();
                
                $("#Banner_campaign_duration").remove();
            });
        ');

cs()->registerScript('banner-colision', '
        /**
        * Update content of info box to display if the banner can be published 
        * for the time period user selected. It banners unpublishing option
        * for publishing banners.
        * Also diables publishing button.
        */
        function formatBannerColision(input){
            console.log(input);
            $infoBox = $("#publishing-info");
            $button = $("#publish-button");
            var html = "<p>" + input.limits + "</p>";
            
            if (input.colisions.length){
                html += "<div>These banners are published at the same time:</div><ul>";
                for (i in input.colisions) {
                    html += "<li><b>" + input.colisions[i].title + "</b><br />" + input.colisions[i].start_date + " - " + input.colisions[i].end_date + "</li>";
                }
                html += "</ul>";
            }
            
            if ($button.length && input.canPublish){
                $button.removeAttr("disabled");
            } else {
                $button.attr("disabled", "disabled");
            }

            $infoBox.html(html);
            refreshWookmark();
        }
        
        // render limitations the first time it is loaded
        formatBannerColision(' . json_encode($info) . ');
        
        function checkColisions(){
            $.ajax({
                data: "bannerId=' . $model->banner_id . '&startDate=" + escape($("#Banner_start_date").val()) + "&endDate=" + escape($("#Banner_end_date").val()),
                type: "get",
                dataType: "json",
                url: "' . url('/banner/getPublishingInfo') . '",
                success: function(response){
                    formatBannerColision(response);
                }
            });
        }

        $("#Banner_start_date").change(checkColisions);
        $("#Banner_end_date").change(checkColisions);
        
        ');

$this->beginWidget('application.components.widgets.AOPanelFoot');

$this->endWidget();

$this->endWidget();
?>

protected/views/banner/_phone_preview.php
<?php

// phone size - 418 x 764
// screen size - 320 x 480
// smaller screen size - 240 x 320

?>

<div style="width: 410px; height: 756px; background-image: url(<?php echo url('/images/iphone_preview.jpg')?>); margin-left: 70px;">
    <div id="phone-preview" style="width: 320px; height: 50px; position: relative; float: left; background-image: url(<?php echo $previewUrl ?>); top: 578px; left: 46px; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;"></div>
</div>

protected/views/banner/disabled.php
<?php
$this->pageTitle = 'Banners are not activated';
$this->beginWidget('bootstrap.widgets.TbHeroUnit', array('heading' => 'Banners are not activated')); ?>
<p>Your account subscription does not have banners feature activated yet. If you would like to publish a banner on the AUSA Offers App, please contact your support team to activate this feature.</p>

<?php
$this->endWidget();
?>

protected/views/banner/index.php
<?php
$this->layout = '//layouts/full';

if (app()->user->IsSalesman() || app()->user->IsAdmin()) {
    $breadcrumbs = array(
        'My Dashboard' => app()->user->getHomeUrl(),
        Vendor::model()->findByPk(app()->user->getActiveVendor())->vendor_name . ' Dashboard' => url('vendor/dashboard'),
        'Banners',
    );
} else {
    $breadcrumbs = array(
        'My Dashboard' => url('vendor/dashboard'),
        'Banners',
    );
}

$dataArray = array(
    'type' => 'striped bordered condensed',
    'dataProvider' => $dataProvider,
    'columns' => array(
        'banner_name',
        array(
            'header' => 'Banner',
            'type' => 'raw',
            'value' => '"<img class=\"offer-preview-icon\" src=\"" . $data->getImageUrl(240) . "\" alt=\"preview\" />"'),
        array('name' => 'status', 'type' => 'raw', 'value' => '$data->getColoredStatus()'),
        array('name' => 'start_date', 'type' => 'raw', 'header' => 'Dates', 'value' => '$data->getDatesForGrid()'),
        array('header' => 'Progress', 'type' => 'raw', 'value' => '$data->getStatsForGrid()'),
        array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{update}',
        ),
    ),
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));
?>

<!--
<?php $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => true)); ?>
<div class="widget-content">
    <h2>Banners</h2>
    <div>
        <p>
            <b>Active:</b> <?php echo $vendor->getTotalActiveBanners() ?>
        </p>
        <p>
            <b>Expired:</b> <?php echo $vendor->getTotalExpiredBanners() ?>
        </p>
    </div>
</div>
<?php $this->endWidget(); ?>

<?php $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => true)); ?>
<div class="widget-content dashboard no-head-foot">
<?php
$this->widget('application.components.widgets.AODashboard', array('items' => array(
        'createOffer' => array('text' => 'Add a banner', 'icon' => 'dashboard-add', 'url' => url('/banner/create')),
        //'offerReport' => array('text' => 'View Reports', 'icon' => 'dashboard-add', 'url' => url('/banner/reports')),
        //'subscription' => array('text' => 'Extend my subscription', 'icon' => 'dashboard-add', 'url' => url('/vendor/subscription')),
        'helpMember' => array('text' => 'Need Help?', 'icon' => 'dashboard-help', 'url' => '#')), 'multiCol' => false));
?>
</div>
<?php $this->endWidget(); ?>
-->

<div class="ausa-contentMain row-fluid">

    <?php
    $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false));
    $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'Your Banners'));
    $this->widget('ausa.widgets.AOButtonGroup', array(
        'type' => '',
        'buttons' => array(
            array('icon' => 'cog', 'items' => array(
                    array('label' => 'Create Banner', 'icon' => 'plus', 'url' => url('/banner/create')),
                    '---',
                    array('label' => 'Get Help', 'icon' => 'question-sign', 'url' => '#'),
            )),
        ),
    ));
    $this->endWidget();

    $this->widget('bootstrap.widgets.TbGridView', $dataArray);

    $this->endWidget();
    ?>  