protected/controllers/SubscriptionController.php
<?php

class SubscriptionController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/full';

    public function filters() {
        return array(
            'https +update',
        );
    }

    public function actionIndex($id = null) {
        if ($id == null) {
            $id = app()->user->getActiveVendor();
        }

        $vendor = Vendor::model()->with(array('plan'))->findByPk($id);
        Shared::debug("actionIndex ->" . $vendor->plan_id);
        //first check if this user has access to this particular vendor
        if (Auth::hasVendorAccess($vendor)) {
            if ($vendor->plan_id) {
                $model = new Subscription();
                $model->initSubscription($vendor);
                $this->render('subscription_info', array(
                    'model' => $model,
                    'vendor' => $vendor,
                    'plan' => $vendor->plan,
                ));
            } else {
                $this->redirect(url('/subscription/plan/' . $id));
            }
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    /**
     * Cancel recurring subscription on the payment gateway
     */
    public function actionUnsubscribe($id = null) {
        if ($id == null) {
            $id = app()->user->getActiveVendor();
        }
        $vendor = Vendor::model()->with(array('users', 'plan'))->findByPk($id);

        if (Auth::hasVendorAccess($vendor)) {
            $subscription = new Subscription();
            $subscription->initSubscription($vendor);

            Shared::debug($_POST);

            if (isset($_POST['unsubscribe'])) {
                $subscription->cancelSubscription($vendor);
                app()->user->setFlash('success', 'Your recurring payment has been cancelled.');
                app()->user->redirectHome();
            }

            if ($subscription->currentlyRecurring) {
                $this->render('unsubscribe', array(
                    'model' => $vendor
                ));
            } else {
                app()->user->setFlash('error', 'There is no recurring payment set.');
                app()->user->redirectHome();
            }
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    public function actionPlan($id = null, $p = null) {
        if ($id == null) {
            $id = app()->user->getActiveVendor();
        }
        $vendor = Vendor::model()->with(array('users', 'plan'))->findByPk($id);
        //Shared::debug("actionIndex ->".$vendor->plan_id);

        if (Auth::hasVendorAccess($vendor)) {
            if ($p != null) {
                $plan = Plan::model()->findByPk((int) $p);
                if (is_object($plan) && $plan->hasAccess()) {
                    $vendor->plan_id = $plan->plan_id;
                    $vendor->save(false, array('plan_id'));
                }
            }

            if ($vendor->plan_id && !app()->user->isAdmin()) {
                $this->redirect(url('/subscription/index/' . $id));
            }
            if (app()->user->isAdmin()) {
                $criteria = new CDbCriteria;
                $criteria->condition = 'active = 1';
                $availablePlans = Plan::model()->findAll($criteria);
            } else if (app()->user->isSalesman()) {
                $criteria = new CDbCriteria;
                $criteria->condition = 'active = 1 AND (access_level="public" OR access_level="st")';
                $availablePlans = Plan::model()->findAll($criteria);
            } else {
                $criteria = new CDbCriteria;
                $criteria->condition = 'active = 1 AND access_level="public"';
                $availablePlans = Plan::model()->findAll($criteria);
            };

            $this->render('select_plan', array(
                'vendor' => $vendor,
                'availablePlans' => $availablePlans,
            ));
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    public function actionUpdate($id, $p = 2) {

        $vendor = Vendor::model()->with('users', 'plan')->findByPk($id);
        //Shared::debug("within actionUpdate");
        //first check if this user has access to this particular vendor
        if (Auth::hasVendorAccess($vendor)) {
            $model = new Subscription();

            Shared::debug($vendor->plan);
            if (!$vendor->plan) { //Todo: Need to revisit this. Can a vendor have pg_id and not plan_id? or have plan_id and not pg_id?
                Shared::debug("Could not find vendor->plan");
                $vendor->plan_id = (int) $p;
                $vendor->plan = Plan::model()->findByPk($vendor->plan_id);
                Shared::debug($vendor->plan);
            }

            $model->initSubscription($vendor);
            //Shared::debug("has vendor access");
            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model);
            Shared::debug($_REQUEST);

            if (isset($_POST['Subscription'])) {
                Shared::debug($_POST);
                $model->attributes = $_POST['Subscription'];
                // Shared::debug($model->attributes);
                $model->validate();
                // Shared::debug("post subsciption is set");

                if (!$model->hasErrors()) {
                    //Shared::debug("it is valid");
                    // disable validation when saving
                    Shared::debug("Run saving methods here.. ");
                    $model->save($vendor);

                    //Shared::debug($model);

                    $vendor->max_offers = $model->maxOffers;
                    $vendor->max_banners = $model->maxBanners;
                    $vendor->max_branches = $model->maxBranches;
                    $vendor->max_categories = $model->maxCategories;
                    if($vendor->plan->free_duration > 0){
                        $days = $vendor->plan->free_duration;
                    }else{
                        $days = 33;
                    }
                    $vendor->expiration = date("Y-m-d", strtotime(date("Y-m-d") . ' +'. $days));
                    //Shared::debug($vendor->max_categories);
                    $vendor->updated_on = date("Y-m-d H:i:s");
                    $vendor->save(false);


                    if (isset($_POST['isAjaxRequest'])) {
                        app()->user->setFlash('success', 'Subscription changes have been saved.');
                        echo $vendor->vendor_id;
                        app()->end();
                    } else {
                        $this->redirect(array('dashboard'));
                    }
                } else {
                    //Shared::debug("model has errors");
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        echo $errors . '</ul>';
                        app()->end();
                    }
                }
            }

            $this->render('update', array(
                'model' => $model,
                'vendor' => $vendor,
                'plan' => $vendor->plan,
            ));
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    public function actionUpdateBilling($id) {
        $vendor = Vendor::model()->findByPk($id);
        //Shared::debug("within actionUpdateBilling");
        //first check if this user has access to this particular vendor
        if (Auth::hasVendorAccess($vendor)) {
            $model = new Subscription();
            $model->initSubscription($vendor);
            //Shared::debug($model);
            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model);

            if (isset($_POST['Subscription'])) {
                Shared::debug($_POST);
                $model->attributes = $_POST['Subscription'];
                // Shared::debug($model->attributes);
                $model->validate();
                Shared::debug($model->getErrors());
                // Shared::debug("post subsciption is set");

                if (!$model->hasErrors()) {
                    //Shared::debug("it is valid");
                    // disable validation when saving
                    Shared::debug("Run SOAP methods here to update Customer Payment Method.. ");
                    Shared::debug($model);
                    //Save Vendor here first TODO
                    //Execute SOAP function here..
                    //$model->quickUpdatePaymentMethod($vendor);
                    $model->save($vendor);
                    app()->user->setFlash('success', 'Payment information has been saved.');
                    echo "1";
                    app()->end();
                } else {
                    Shared::debug("model has errors");
                    if (isset($_POST['isAjaxRequest'])) {
                        $errors = '<ul>';
                        foreach ($model->getErrors() as $error) {
                            $errors .= '<li>' . $error[0] . '</li>';
                        }
                        echo $errors . '</ul>';
                        app()->end();
                    }
                }
            }


            $this->render('update_billing', array(
                'model' => $model,
                'vendor' => $vendor,
            ));

protected/views/subscription/_billing_contact.php
<?php
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'contact-info',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => false));

if ($model->firstName && $model->lastName)
    echo $form->customRow($model, 'name', 'Name', '<div style="margin-bottom:10px;">' . $model->firstName . ' ' . $model->lastName . '</div>');
if ($model->company)
    echo $form->customRow($model, 'company', 'Company', '<div style="margin-bottom:10px;">' . $model->company . '</div>');
echo $form->customRow($model, 'bill_add', 'Billing Address', '<div>' . $model->street . ($model->street2 ? ', ' . $model->street2 : '') . '</div>'
        . '<div' . ($model->country ? '' : ' style="margin-bottom:10px;"') . '>' . $model->city . ($model->state ? ', ' . $model->state : '') . ($model->zip ? ' &nbsp;' . $model->zip : '') . '</div>'
        . ($model->country ? '<div style="margin-bottom:10px;">' . $model->country . '</div>' : '')
);
if ($model->phone)
    echo $form->customRow($model, 'phone', 'Phone', '<div style="margin-bottom:10px;">' . $model->phone . '</div>');
if ($model->email)
    echo $form->customRow($model, 'email', 'Email', '<div style="margin-bottom:10px;">' . $model->email . '</div>', array('style'=>'border:0px;'));

$this->endWidget();
?>

protected/views/subscription/_billing_contact_form.php
<?php

$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'billing-contact',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => false));


echo $form->errorSummary($model);
//Shared::debug($model);


echo $form->textFieldRow($model, 'firstName', array('class' => 'span'));

echo $form->textFieldRow($model, 'lastName', array('class' => 'span'));

echo $form->textFieldRow($model, 'company', array('class' => 'span'));

echo $form->textFieldRow($model, 'street', array('class' => 'span'));

echo $form->textFieldRow($model, 'street2', array('class' => 'span'));

echo $form->textFieldRow($model, 'city', array('class' => 'span'));

echo $form->textFieldRow($model, 'state', array('class' => 'span'));

echo $form->textFieldRow($model, 'zip', array('class' => 'span'));

echo $form->textFieldRow($model, 'country', array('class' => 'span'));

echo $form->textFieldRow($model, 'phone', array('class' => 'span'));

echo $form->textFieldRow($model, 'email', array('class' => 'span'));


$this->endWidget();
?>

protected/views/subscription/_billing_form.php
<?php
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'billing-form',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => false));

echo $form->errorSummary($model);
//Shared::debug($model);


$button = $this->widget('bootstrap.widgets.TbButtonGroup', array(
    'type' => 'default',
    'toggle' => 'radio',
    'buttons' => array(
        array('label' => 'Credit Card', 'active' => $model->paymentType == 'cc' ? true : false, 'htmlOptions' => array('id' => 'cc-button')),
        array('label' => 'ACH / E-Check', 'active' => $model->paymentType == 'check' ? true : false, 'htmlOptions' => array('id' => 'ach-button')),),
    'htmlOptions'=>array('style'=>'text-align:center; margin-bottom:10px;'),
), true);
echo $form->customRow($model, 'paymentType', 'Payment Type', $button, array('hint' => 'Please choose your method of payment.'));
echo CHtml::activeHiddenField($model, 'paymentType');

cs()->registerScript('payment-type', '
            
            $("#cc-button").click(function(){
                if (!$(this).hasClass("active")){
                    $("#Subscription_paymentType").val("cc");
                    $("#ach-fields").hide();
                    $("#cc-fields").show();
                }
            });
            $("#ach-button").click(function(){
                if (!$(this).hasClass("active")){
                    $("#Subscription_paymentType").val("check");
                    $("#cc-fields").hide();
                    $("#ach-fields").show();
                }
            });
            $("form#remove").remove();
        ');

 //preselect the payment type button on page load
if (($model->paymentType == "cc") || (!$model->paymentType)) {
    cs()->registerScript('payment-type-toggle', '
            
            $("#cc-button").button("toggle");
            $("#ach-fields").hide();
            $("#cc-fields").show();
            
        ');
} elseif ($model->paymentType == "check") {
    cs()->registerScript('payment-type-toggle', '
            
            $("#ach-button").button("toggle");
            $("#cc-fields").hide();
            $("#ach-fields").show();
            
        ');
}
?>

<div id="cc-fields">
    <?php
    //echo $form->dropDownListRow($model, 'cardType', $model->getPaymentTypes());

    echo $form->textFieldRow($model, 'cardNumber', array('class' => 'span', 'maxlength' => 16));

    echo $form->textFieldRow($model, 'cardCode', array('class' => 'span', 'maxlength' => 4));
    
    $expMonthInput = $form->dropDownList($model, 'cardExpMonth', Plan::$months, array('style' => 'width:40%; margin-right:20px;'));
    $expYearInput = $form->dropDownList($model, 'cardExpYear', Plan::getExpYearArray(11), array('style' => 'width:25%;'));

    //$expMonthInput = $this->widget('CActiveForm',array('id'=>'remove'))->dropDownList($model,'cardExpMonth',Plan::$months,array('style'=>'width:40%; margin-right:20px;'));
    //$expYearInput = $this->widget('CActiveForm',array('id'=>'remove'))->dropDownList($model,'cardExpYear',Plan::getExpYearArray(11),array('style'=>'width:25%;'));
    
    echo $form->customRow($model,'exp_date','Expiration Date',$expMonthInput.$expYearInput, array('style'=>'border:0px;'));
    
    ?>

</div>

<div id="ach-fields" class="no-foot" style="background-color: #FFF;">

    <?php
    echo $form->textFieldRow($model, 'achAccount', array('class' => 'span', 'maxlength' => 10));

    echo $form->textFieldRow($model, 'achRouting', array('class' => 'span', 'maxlength' => 10));

    ?>
</div>
<?php $this->endWidget(); ?>

protected/views/subscription/_billing_info.php
<?php
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'billing-info',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => false));

if ($model->paymentType == "cc") {
    echo $form->customRow($model,'credit_card','Payment Type','<div class="cc-payment-type" style="margin-bottom:10px;"><span>Credit Card</span></div>');
    echo $form->customRow($model,'credit_card_num','Credit Card Number','<div style="margin-bottom:10px;">'.$model->cardNumber.'</div>');
    echo $form->customRow($model,'credit_card_exp','Expiration Date','<div style="margin-bottom:10px;">'.$model->cardExpMonth.'-'.$model->cardExpYear.'</div>', array('style'=>'border:0px;'));
} elseif($model->paymentType == "check") {
    echo $form->customRow($model,'check','Payment Type','<div style="margin-bottom:10px;">ACH / E-Check</div>');
    echo $form->customRow($model,'check_acc_num','Bank Account Number','<div style="margin-bottom:10px;">'.$model->achAccount.'</div>');
    echo $form->customRow($model,'check_rt_num','Routing Number','<div style="margin-bottom:10px;">'.$model->achRouting.'</div>', array('style'=>'border:0px;'));
}
$this->endWidget();
?>

protected/views/subscription/_subscription_form.php
<?php
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'subscription-form',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => false));


echo $form->errorSummary($model);

if (!$model->currentlyRecurring) {
    $button = $this->widget('bootstrap.widgets.TbButtonGroup', array(
        'type' => 'default',
        'toggle' => 'radio',
        'buttons' => array(
            array('label' => 'Recurring Payments', 'active' => $model->paymentMode == 'recurring' ? true : false, 'htmlOptions' => array('id' => 'recurring-button')),
            array('label' => 'Single Payment', 'active' => $model->paymentMode == 'single' ? true : false, 'htmlOptions' => array('id' => 'single-button')),),
        'htmlOptions' => array('style' => 'text-align:center; margin-bottom:10px;'),
            ), true);
    echo $form->customRow($model, 'paymentMode', 'Payment Mode', $button, array('hint' => 'Please choose your mode of payment.'));
    echo CHtml::activeHiddenField($model, 'paymentMode');

    cs()->registerScript('payment-mode',
            '$("#recurring-button").click(function(){
                if (!$(this).hasClass("active")){
                    $("#Subscription_paymentMode").val("recurring");
                    $("#recurring-fields").show();
                    $("#Subscription_paymentAmount").val($("#Subscription_monthlyRecurringPrice").val());
                    $("#Subscription_tax").val(($("#Subscription_monthlyRecurringPrice").val() * 0.0825).toFixed(2));
                    

                    var noOfBanners = $("#Subscription_maxBanners").val();
                if(noOfBanners > 0){
                    $("#Subscription_subscriptionNotes").val("Monthly automatic withdrawal of $"
                    + $("#Subscription_paymentAmount").val() +
                    " + Tax for "
                    + $("#Subscription_maxBanners").val() +
                    " banner slot(s) and "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }else{
                    $("#Subscription_subscriptionNotes").val("Monthly automatic withdrawal of $"
                    + $("#Subscription_paymentAmount").val() +
                    " for "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }
            }});
            
            $("#single-button").click(function(){
                if (!$(this).hasClass("active")){
                    $("#Subscription_paymentMode").val("single");
                    $("#recurring-fields").hide();
                    $("#Subscription_paymentAmount").val($("#Subscription_singlePaymentPrice").val());
                    $("#Subscription_tax").val(($("#Subscription_singlePaymentPrice").val() * 0.0825).toFixed(2));
                    


                    var noOfBanners = $("#Subscription_maxBanners").val();
                if(noOfBanners > 0){
                    $("#Subscription_subscriptionNotes").val("Single Payment of $"
                    + $("#Subscription_paymentAmount").val() +
                    " + Tax for "
                    + $("#Subscription_maxBanners").val() +
                    " banner slot(s) and "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }else{
                    $("#Subscription_subscriptionNotes").val("Single Payment of $"
                    + $("#Subscription_paymentAmount").val() +
                    " for "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }
                

                }
            });
            
            
        ');

///Preselect the payment Mode button
    if (($model->paymentMode == "recurring") || (!$model->paymentMode)) {
        cs()->registerScript('payment-mode-toggle', '$("#recurring-button").button("toggle");
                $("#recurring-fields").show();');
    } elseif ($model->paymentMode == "single") {
        cs()->registerScript('payment-mode-toggle', '$("#single-button").button("toggle");
            $("#recurring-fields").hide();');
    }
} else {
    echo $form->textFieldRow($model, 'paymentMode', array('class' => 'span', 'disabled' => 'disabled'));
}


cs()->registerScript('subscription-notes', '
            
            $("#Subscription_maxOffers, #Subscription_maxBanners, #Subscription_paymentAmount").keyup(function(){
                
                var noOfBanners = $("#Subscription_maxBanners").val();
                if((noOfBanners > 0) && ($("#Subscription_paymentMode").val() == "recurring")){
                    $("#Subscription_subscriptionNotes").val("Monthly automatic withdrawal of $"
                    + $("#Subscription_paymentAmount").val() +
                    " + Tax for "
                    + $("#Subscription_maxBanners").val() +
                    " banner slot(s) and "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }else if((noOfBanners > 0) && ($("#Subscription_paymentMode").val() == "single")){
                    $("#Subscription_subscriptionNotes").val("Single Payment of $"
                    + $("#Subscription_paymentAmount").val() +
                    " + Tax for "
                    + $("#Subscription_maxBanners").val() +
                    " banner slot(s) and "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }else if($("#Subscription_paymentMode").val() == "single"){
                    $("#Subscription_subscriptionNotes").val("Single Payment of $"
                    + $("#Subscription_paymentAmount").val() +
                    " for "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }else{
                    $("#Subscription_subscriptionNotes").val("Monthly automatic withdrawal of $"
                    + $("#Subscription_paymentAmount").val() +
                    " for "
                    + $("#Subscription_maxOffers").val() +
                    " offer slot(s)."
                     );
                }
            });
            
        ');

if ($vendor->plan->max_banners > 0) {
    echo $form->textFieldRow($model, 'maxBanners', array('class' => 'span', 'maxlength' => 1));
}
echo $form->textFieldRow($model, 'maxOffers', array('class' => 'span', 'maxlength' => 1));

cs()->registerScript('tax-calculation', '
            $("#Subscription_paymentAmount").keyup(function(){
                $("#Subscription_tax").text(($("#Subscription_paymentAmount").val() * 0.0825).toFixed(2));
            });
            
        ');

if ((app()->user->isAdmin()) || (app()->user->isSalesman())) {
    echo $form->textFieldRow($model, 'paymentAmount', array('class' => 'span', 'style' => 'width:30%;'));
} else {
    echo $form->textFieldRow($model, 'paymentAmount', array('class' => 'span', 'disabled' => 'disabled', 'style' => 'width:30%;'));
}
//echo $form->textFieldRow($model, 'tax', array('class' => 'span', 'disabled' => 'disabled', 'style' => 'width:30%;'));
echo $form->customRow($model, 'tax', "Tax", '<div id="Subscription_tax" style="margin-bottom:10px;">' . $model->tax . '</div>');
echo CHtml::activeHiddenField($model, 'singlePaymentPrice');
echo CHtml::activeHiddenField($model, 'monthlyRecurringPrice');
?>
<div id="recurring-fields">
    <?php
//echo $form->dropDownListRow($model, 'recurringSchedule', $model->recurringSchedule);
    //echo $form->textFieldRow($model, 'recurringSchedule', array('class' => 'span', 'disabled' => 'disabled'));
    echo $form->customRow($model, 'recurringSchedule', "Payment Schedule", '<div style="margin-bottom:10px;">Monthly</div>');
    if (!$model->currentlyRecurring) {
        echo $form->datepickerRow($model, 'firstPaymentDate', array('class' => 'span'));
    }
    ?>
</div>
<?php
if (!$model->currentlyRecurring) {
//    if ((int) $vendor->plan->offer_duration >= (int) $vendor->plan->banner_duration) {
//        echo $form->customRow($model, 'numLeft', "Duration", '<div style="margin-bottom:10px;">' . $vendor->plan->offer_duration . ' Months</div>');
//        //$model->numLeft = $vendor->plan->offer_duration;
//    } else {
//        echo $form->customRow($model, 'numLeft', "Duration", '<div style="margin-bottom:10px;">' . $vendor->plan->banner_duration . ' Months</div>');
//        //$model->numLeft = $vendor->plan->banner_duration;
//    }
    //echo $form->customRow($model, 'numLeft', 'Duration (months)', $model->numLeft);

    echo $form->customRow($model, 'numLeft', "Duration", '<div style="margin-bottom:10px;">' . $model->numLeft . ' Months</div>');
    echo CHtml::activeHiddenField($model, 'numLeft');
} else {
    if ($model->numLeft != -1) {
        echo $form->customRow($model, 'numLeft', "Months Left", '<div style="margin-bottom:10px;">' . $model->numLeft . ' Months</div>');
    }
}



//if ((app()->user->isAdmin()) || (app()->user->isSalesman())) {
//echo $form->textFieldRow($model, 'discountPercentage', array('class' => 'span', 'maxlength' => 2));
/*
 $discSlider = $this->widget('zii.widgets.jui.CJuiSlider', array(
     'value' => 0,
     'id' => 'discountSlider',
     'options' => array(
         'min' => 0,
         'max' => 30,
         'range' => 'min',
         'slide' => 'js:function(event, ui) {
             $("#percent-display").text(ui.value + "%");
             $("#Subscription_discountPercentage").val(ui.value);
         }',
     ),
     'htmlOptions' => array(
         'class' => 'progress progress-warning ausaProgress',
     ),
 ), true);
 $discSlider .= '<div id="percent-display" style="float:right; margin-top:-30px; margin-right:20px; font-size:14px;"></div>';
 
 echo $form->customRow($model, 'discount', 'Apply a Discount', $discSlider, array('hint' => 'Drag the slider to apply a discount percentage of up to 30%.'));
 
 echo '<input type="hidden" id="Subscription_discountPercentage" />';
//}
//echo $form->datepickerRow($model, 'nextPaymentDate', array('class' => 'span'));
//echo $form->datepickerRow($model, 'contractExpiration', array('class' => 'span'));
*/
echo $form->textAreaRow($model, 'subscriptionNotes', array('class' => 'span', 'rows' => 4, 'maxlength' => 1000));

$this->endWidget();
?>

protected/views/subscription/_subscription_status.php

<?php

$this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => true));
$this->widget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons help', 'panelTitle' => 'Subscription Status'));

$subscription = new Subscription();
$subscription->initSubscription($model);

$subStatus = $model->getSubscriptionStatus($subscription);
//display these attributes..
$attributes = array(array('label' => 'Subcsription Status', 'type' => 'raw', 'value' => $model->getColoredStatus($subscription)));

if ($subStatus != Vendor::SUB_NOT_ACTIVE) {
    if ($subStatus != Vendor::SUB_EXPIRED) {
        $attributes[] = array('name' => 'expiration', 'label' => 'Expires', 'type' => 'raw', 'value' => Shared::formatShortUSDate($model->expiration));
    } else {
        $attributes[] = array('name' => 'expiration', 'label' => 'Expired On', 'type' => 'raw', 'value' => Shared::formatShortUSDate($model->expiration));
    }
}

$labelVar = "Pay Now And Activate";
$labelIcon = "icon-shopping-cart white";
$labelType = "success";
$labelURL = '/subscription/update/' . $model->vendor_id;
if ($subStatus == Vendor::SUB_ACTIVE) {
    $labelVar = "My Payment Information";
} else if ($subStatus == Vendor::SUB_EXPIRE_SOON) {
    $labelVar = "Pay Now and Extend";
}

$ccStatus = $subscription->getCCStatus();

if ($ccStatus != Subscription::CARD_ACTIVE && $subscription->paymentType == "cc") {
    if ($ccStatus == Subscription::CARD_EXPIRED) {
        $attributes[] = array('name' => 'paymentDetails', 'label' => 'Payment Details', 'type' => 'raw', 'value' => $subscription->getColoredCCStatus($subscription));
    } else if ($ccStatus == Subscription::CARD_EXPIRE_SOON) {
        $attributes[] = array('name' => 'paymentDetails', 'label' => 'Payment Details', 'type' => 'raw', 'value' => $subscription->getColoredCCStatus($subscription));
    } else {
        $attributes[] = array('name' => 'paymentDetails', 'label' => 'Payment Details', 'type' => 'raw', 'value' => $subscription->getColoredCCStatus($subscription));
    }

    $labelVar = "Update Payment Information";
    $labelIcon = "legal white";
    $labelType = "danger";
    $labelURL = '/subscription/updatebilling/' . $model->vendor_id;
}

$this->widget('bootstrap.widgets.TbDetailView', array(
    'data' => $model,
    'attributes' => $attributes)
);


$this->beginWidget('application.components.widgets.AOPanelFoot');

// make it not too obvious and display it only if the customer is subscribed.
if ($subscription->currentlyRecurring){
    echo CHtml::link("Unsubscribe", url('subscription/unsubscribe'), array('style' => 'float: left; margin: 10px 15px;'));
}

$this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'link',
    'icon' => $labelIcon,
    'type' => $labelType,
    'size' => 'small',
    'url' => url($labelURL),
    'label' => $labelVar,
    'htmlOptions' => array('style' => 'margin: 7px 10px 0px 8px; float: right',)
));
$this->endWidget();
$this->endWidget();
?>