protected/controllers/UserController.php
<?php

class UserController extends Controller {

    public function filters() {
        return array(
            'https +login', // Force https, but only on login page
            'entity + forgotpassword, newPassword, verify',
        );
    }

    public function actionIndex() {
        if (app()->user->isAdmin()) {
            $id = app()->user->getUser()->user_id;
            $model = User::model()->findByPk($id);
            $dataProvider = new CActiveDataProvider('User');
            $this->render('index', array(
                'dataProvider' => $dataProvider,
                'model' => $model,
            ));
        } else {
            Yii::app()->user->loginRequired();
        }
    }

    // Uncomment the following methods and override them if needed
    /*
      public function filters()
      {
      // return the filter configuration for this controller, e.g.:
      return array(
      'inlineFilterName',
      array(
      'class'=>'path.to.FilterClass',
      'propertyName'=>'propertyValue',
      ),
      );
      } */

    public function actions() {
        // return external action classes, e.g.:
        return array(
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
        );
    }

    /**
     * Displays the login page
     */
    public function actionLogin() {

        $model = new LoginForm;
        $alert = false;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];

            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login()) {
                $user = Yii::app()->user->getUser();

                if (!isset($user->last_login) || !isset($user->email_verified) || (int) ($user->email_verified) < 1 || strlen($user->first_name) < 2 || strlen($user->last_name) < 2) {
                    User::model()->updateByPk($user->user_id, array('last_login' => new CDbExpression('NOW()')));
                    if (isset($_POST['ajax'])) {
                        echo url('/user/firstlogin');
                        app()->end();
                    }
                    $this->redirect(url('/user/firstlogin'));
                } else {
                    User::model()->updateByPk($user->user_id, array('last_login' => new CDbExpression('NOW()')));
                    if (isset($_POST['ajax'])) {
                        echo app()->user->getHomeUrl();
                        app()->end();
                    } else {
                        $this->redirect(app()->user->getHomeUrl());
                    }
                    app()->user->redirectHome();
                }
            } else {
                if (isset($_POST['ajax'])) {
                    echo "bad";
                    app()->end();
                } else {
                    $alert = true;
                }
            }
        }

        // display the login form
        $this->render('login', array('model' => $model, 'alert' => $alert));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    /**
     * Create new login. Only admin should be able to do it.
     */
    public function actionCreate($vendor_id = null, $chapter_id = null, $st_id = null) {
        // check that admin is creating another user
        //$this->authAdminOnly();
        if (app()->user->isAdmin() || app()->user->isSalesman()) {
            $model = new User('create');
            // Shared::debug($_POST);

            $vendor = $chapter = $st = null;

            if ($vendor_id) {
                $vendor = Vendor::model()->findByPk($vendor_id);
            } else if ($chapter_id) {
                $chapter = Chapter::model()->findByPk($chapter_id);
            } else if ($st_id) {
                $st = SalesTeam::model()->findByPk($st_id);
            }


            if (isset($_POST['User'])) {
                $model = User::create($_POST['User']);
                if ($model->save()) {
                    if (isset($_POST['vendor_id']) && is_numeric($_POST['vendor_id'])) {//check to see if vendor is being added.
                        $userVendor = UserVendor::create($model, $_POST['vendor_id']);
                        $userVendor->save(); //also save the user_vendor join
                    }

                    if (isset($_POST['chapter_id']) && is_numeric($_POST['chapter_id'])) {//check to see if vendor is being added.
                        $userChapter = UserChapter::create($model, $_POST['chapter_id']); //also save the user_chapter join
                        $userChapter->save();
                    }

                    if (isset($_POST['sales_team_id']) && is_numeric($_POST['sales_team_id'])) {//check to see if vendor is being added.
                        $userSt = UserSt::create($model, $_POST['sales_team_id']); //also save the user_st join..
                        $userSt->save();
                    }

                    $this->redirect(url('/user'));
                    Yii::app()->end();
                }
            }
            // render the create form
            $this->render('create', array(
                'model' => $model,
                'vendor' => $vendor,
                'chapter' => $chapter,
                'st' => $st,
            ));
        } else {
            $this->redirect(url('/vendor/register'));
            //app()->user->loginRequired();
        }
    }

    public function actionRegister() {
        $this->redirect(url('/vendor/register'));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id) {

        if (app()->user->id == $id || app()->user->IsAdmin()) {

            // some authentication is required

            $model = $this->loadModel($id);
            $model->scenario = 'update';

            $this->performAjaxValidation($model);

            //Now find out what Sales Team or Chapter or Vendor this user is assigned to.. 
            $vendor = $chapter = $st = null;
            $vArray = $model->getVendorIds(true, true); //reload=true; but get onlyVendors here = true
            if (isset($vArray[0])) {
                $vendor = Vendor::model()->findByPk($vArray[0]);
            }

            $cArray = $model->getChapterIds(); //reload=true; but get onlyVendors here = true
            if (isset($cArray[0])) {
                $chapter = Chapter::model()->findByPk($cArray[0]);
            }

            $stArray = $model->getStIds(true, true); //reload=true; but get onlyVendors here = true
            if (isset($stArray[0])) {
                $st = SalesTeam::model()->findByPk($stArray[0]);
            }

            if (isset($_POST['User'])) {
                $model->attributes = $_POST['User'];
                //$model->setPassword($_POST['User']['password']);
                if ($model->save()) {
                    app()->user->setFlash('success', 'Account setting have been saved.');

                    //Shared::debug($_POST);
                    //(isset($_POST['Vendors'])) {
                    // N squared is not good
                    //foreach ($_POST['Vendors']['user_vendor'] as $id => $vendorId) {
                    // add remove user from vendor list
                    //$found = false;
                    //foreach ($model->vendors as $vendor) {
                    //if ($vendor->vendor_id == $vendorId) {
                    //$found = true;
                    //}
                    //}
                    //if (!$found) {
                    //$userVendor = UserVendor::create($user, $vendorId);
                    //Shared::debug($userVendor);
                    //if ($userVendor != null)
                    //$userVendor->save();
                    //}
                    //}
                    //}
                    //}else {
                    //Shared::debug("errors are everywhere");
                }
            }

            // do not edit the hash
            $model->password = '';

            $this->render('update', array(
                'model' => $model,
                'vendor' => $vendor,
                'chapter' => $chapter,
                'st' => $st,
            ));
        } else {
            throw new CHttpException(403, 'Access Denied.');
        }
    }

    public function actionPassword($id) {
        $user = app()->user->getUser();
        if (isset($user->user_id) && $user->user_id === $id || app()->user->isAdmin()) {
            $model = $this->loadModel($id);
            $model->setScenario('changePassword');
            if (isset($_POST['User'])) {
                $model->attributes = $_POST['User'];
                if ($model->validate()) {
                    $model->password = sha1($model->salt . $_POST['User']['pass1']);
                    if ($model->save()) {
                        app()->user->setFlash('success', 'Your password has been updated.');
                        $this->redirect(array('update', 'id' => $model->user_id));
                    }
                }
            }

            $this->render('/user/password', array('model' => $model));
        } else {

protected/views/user/_contact_form.php
<?php

// this form is used by admin only to change global user account configuration
// companies have custom forms
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'user-form',
    'htmlOptions' => array('class' => 'no-foot'),
    'enableAjaxValidation' => true,
        ));

echo $form->errorSummary($model);

echo $form->textFieldRow($model, 'email_address', array('class' => 'span', 'maxlength' => 63, 'hint' => 'Email address is used for login, make sure it is unique and correct.'));

echo $form->textFieldRow($model, 'first_name', array('class' => 'span'));

echo $form->textFieldRow($model, 'last_name', array('class' => 'span'));

echo $form->textFieldRow($model, 'phone_number', array('class' => 'span', 'maxlength' => 12));

// only admin and salesman can disable login for this user
if (app()->user->isAdmin()) {
    echo $form->checkBoxRow($model, 'login_disabled');
}
/*
else if (app()->user->isSalesman()) {
    echo $form->checkBoxRow($model, 'login_disabled', array('disabled' => 'disabled'));
}
*/

if (isset($userVendor)) {
    echo $form->checkBoxRow($userVendor, 'send_redemption_email');
}

$this->beginWidget('application.components.widgets.AOPanelFoot');

/* $this->widget('bootstrap.widgets.TbButton', array(
  'buttonType' => $model->isNewRecord ? 'submit' : 'ajaxSubmit',
  'type' => 'success',
  'htmlOptions' => array('style' => 'margin: 7px 5px; float: right', 'onclick' => 'showSuccess(\'Vendor changes updated.\')'),
  'size' => 'small',
  'icon' => 'ok white',
  'label' => $model->isNewRecord ? 'Create' : 'Update',
  ));
  $this->widget('bootstrap.widgets.TbButton', array(
  'buttonType' => 'reset',
  'type' => '',
  'htmlOptions' => array('style' => 'margin: 7px 5px; float: right', 'onclick' => 'showDefault(\'Vendor changes reset.\')'),
  'size' => 'small',
  'icon' => 'remove',
  'label' => $model->isNewRecord ? 'Clear' : 'Cancel',
  )); */

//if (!app()->user->isAdmin()){
    
// listen for email address change and bind event to global update / apply button
if (!$model->isNewRecord){
cs()->registerScript('email-changes', '
var origEmail = "' . $model->email_address . '";
var emailChanged = false;

$("#User_email_address").change(function(){
    if($("#User_email_address").val() != origEmail) {
        console.log("change detected");
        emailChanged = true;
    }
});

$("#apply-vendor-button,#save-vendor-button").click(function(){
    console.log("apply again, mofo");
    if (emailChanged){
        alert("This email is different from our stored email address. Please check your email and confirm the change.");
    }
});
');
}
//}

$this->endWidget();

$this->endWidget();
?>

protected/views/user/_form.php
<?php
if(isset($new)){
    $title = 'Create User';
} else {
    $title = 'Account Settings';
} ?>

<h1 class="title"><?php echo $title; ?></h1>

<?php
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'user-form',
    'enableAjaxValidation' => false,
        ));
?>

<ul class="fields">

    <?php //echo $form->errorSummary($model); ?>

    <?php if ($vendor): ?>
        <li>
            <i class="icon-truck" title="Vendor"></i>
            <?php echo CHtml::tag('span', array('class' => 'uneditable-input'), $vendor->{'vendor_name'}); ?>
            <?php echo CHtml::hiddenField('vendor_id', $vendor->vendor_id); ?>
        </li>
    <?php elseif ($chapter): ?>
        <li>
            <i class="icon-star" title="Chapter"></i>
            <?php echo CHtml::tag('span', array('class' => 'uneditable-input'), $chapter->{'chapter_name'}); ?>
            <?php echo CHtml::hiddenField('chapter_id', $chapter->chapter_id); ?>
        </li>
    <?php elseif ($st): ?>
        <li>
            <i class="icon-group" title="Sales Team"></i>
            <?php echo CHtml::tag('span', array('class' => 'uneditable-input'), $st->{'st_name'}); ?>
            <?php echo CHtml::hiddenField('sales_team_id', $st->sales_team_id); ?>
        </li>
    <?php else: ?>
        <li>
            <i class="icon-truck" title="Vendor"></i>
            <?php echo $form->dropDownList(new Vendor, 'vendor_id', CHtml::listData(Vendor::model()->findAll(), 'vendor_id', 'vendor_name'), array('empty' => '', 'id' => "vendor_id", 'name' => 'vendor_id', 'class' => 'span3')); ?>
        </li>
        <li>
            <i class="icon-star" title="Chapter"></i>
            <?php echo $form->dropDownList(new Chapter, 'chapter_id', CHtml::listData(Chapter::model()->findAll(), 'chapter_id', 'chapter_name'), array('empty' => '', 'id' => "chapter_id", 'name' => 'chapter_id', 'class' => 'span3')); ?>
        </li>
        <li>
            <i class="icon-group" title="Sales Team"></i>
            <?php echo $form->dropDownList(new SalesTeam, 'sales_team_id', CHtml::listData(SalesTeam::model()->findAll(), 'sales_team_id', 'st_name'), array('empty' => '', 'id' => "sales_team_id", 'name' => 'sales_team_id', 'class' => 'span3')); ?>
        </li>
    <?php endif; ?>
    <li>
        <i class="icon-envelope-alt" title="Email Address"></i>
        <?php echo $form->textField($model, 'email_address', array('placeholder' => 'email address', 'maxlength' => 63,)); ?>
    </li>
    <li>
        <i class="icon-user" title="First Name"></i>
        <?php echo $form->textField($model, 'first_name', array('placeholder' => 'first name')); ?>
    </li>
    <li>
        <i class="icon-user" title="Last Name"></i>
        <?php echo $form->textField($model, 'last_name', array('placeholder' => 'last name')); ?>
    </li>
    <li>
        <i class="icon-globe" title="Address"></i>
        <?php echo $form->textField($model, 'address', array('placeholder' => 'address', 'maxlength' => 511)); ?>
    </li>
    <li>
        <i class="icon-phone" title="Phone Number"></i>
        <?php echo $form->textField($model, 'phone_number', array('placeholder' => 'phone number', 'maxlength' => 12)); ?>
    </li>
</ul>
<?php
// visible for admin only
if (app()->user->isAdmin()) {
    echo '<div class="mid-form" style="padding-bottom: 0;">';
    echo $form->checkBoxRow($model, 'super_admin');
    echo $form->checkBoxRow($model, 'login_disabled');
    echo '</div>';

    // company association .. this will be eventually a table
    /* echo $form->dropDownListRow(new Vendor, 'vendor_id', CHtml::listData(Vendor::model()->findAll(), 'vendor_id', 'vendor_name'), array('empty' => '', 'id' => "user_vendor_new",
      'name' => 'Vendors[user_vendor][]')
      ); */
    // edit
}
?>
<div class="mid-form"<?php if(isset($new)){?> style="padding-bottom: 0;"<?php } ?>>
    <span class="login-checkbox pull-left"></span>
    <?php
    $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'label' => $model->isNewRecord ? 'Create' : 'Save Changes',
        'type' => 'primary',
        'htmlOptions' => array('class' => 'pull-right'),
        'block' => true,
        'size' => 'large',
    ));
    ?>
</div>

<?php if(!isset($new)){ ?>
<div class="mid-footer">
    <?php
    $this->widget('bootstrap.widgets.TbButton', array(
        'label' => 'Change Password',
        'type' => 'link',
        'url' => array('/user/password/' . $model->user_id),
        'icon' => 'icon-key',
    ));
    ?>
</div>
<?php } ?>

<?php $this->endWidget(); ?>

protected/views/user/_mobile.php
<?php
$this->pageTitle = Yii::app()->name . ' - Mobile Access';
$this->layout = '//layouts/full';

if (app()->user->IsSalesman() || app()->user->IsAdmin()) {
    $breadcrumbs = array(
        'My Dashboard' => app()->user->getHomeUrl(),
        Vendor::model()->findByPk(app()->user->getActiveVendor())->vendor_name . ' Dashboard' => url('vendor/dashboard'),
        'Mobile Access'
    );
} else {
    $breadcrumbs = array(
        'My Dashboard' => url('vendor/dashboard'),
        'Mobile Access',
    );
}

$this->renderPartial('//layouts/userHeader', array('model' => $vendor, 'breadcrumbs' => $breadcrumbs));
$this->renderPartial('//layouts/vendorHeader', array('model' => $vendor));
?>
<div id="vendor-mainDashboard" style="height: 307px;">
    <div id="map_holder" class="dashboardHighlight" style="padding: 0px; height: 100%; clear: both; overflow: hidden;">
        <div id="map_canvas" style="height: 100%;"></div>
    </div>
</div>
<div class="widget-content dashboard">
    <?php $this->renderPartial('//vendor/dashActions/_dashboardLinks', array('model' => $vendor), false, false); ?>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="ausa-contentMain row-fluid">

    <?php
    $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false));
    $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons marker', 'panelTitle' => 'Mobile Access'));
    /* $this->widget('ausa.widgets.AOButtonGroup', array(
      'type' => '',
      'htmlOptions' => array('id' => 'branch-dropdown'),
      'buttons' => array(
      array('icon' => 'cog', 'items' => array(
      array('label' => 'Add a Branch', 'icon' => 'plus', 'url' => 'create', 'id' => 'create-branch-popup'),
      '---',
      array('label' => 'Get Help', 'icon' => 'question-sign', 'url' => '#'),
      )),
      ),
      )); */
    $this->endWidget();

    // genearate access token
    $model->getAccessToken();
    //Shared::debug($model);
    ?>
    <div>
        Download your mobile app at:
    </div>
    <div>
        Login: <?php echo $model->mobile_username ?><br />
        Pin: <?php echo $model->mobile_password ?><br />
    </div>
    <div class="info">
        Please note that this is a demo account and the app functionality is limited.
    </div>
    <?php
    $this->widget('application.components.widgets.AOPanelFoot');
    $this->endWidget();
    ?>

protected/views/user/_signedin.php
<?php // Delete this ?>

protected/views/user/_signin.php
<?php

// User sign in form which is found on any page in the main menu dropdown.
$model = new LoginForm;
$form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
    'id' => 'login-form',
    'htmlOptions' => array('class' => 'ausa-userSignin'),
    'action' => url('/login'),
    'focus' => true,
        ));

echo $form->textAOFieldRow($model, 'username', array('class' => 'span3', 'tabindex' => '1', 'placeholder' => 'Email', 'maxlength' => 255));
echo $form->passwordAOFieldRow($model, 'password', array('class' => 'span3', 'tabindex' => '2', 'placeholder' => 'Password', 'maxlength' => 32));
echo CHtml::hiddenField('ajax', '1');

echo '<fieldset id="actions">';

$this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'button',
    'type' => 'primary',
    'icon' => 'user white',
    'htmlOptions' => array(
        'id' => 'submit-signin',
         'tabindex' => '4'
    ),
    'loadingText' => '<i class="icon-spinner icon-spin"></i> Sign In',
    'label' => 'Sign In',
));

echo $form->checkBoxAORow($model, 'rememberMe', array('tabindex' => '3'));

echo '</fieldset>';

cs()->registerScript('login-submit', "
function submitLoginForm(){
$.ajax({
    data: $('#login-form').serialize(0),
    type: 'post',
    url: '" . url('/login') . "',
    completedText: 'redirecting...',
    beforeSend: function(){ $('#submit-signin').button('loading') },
    success: function(response){
        if (response == 'bad'){
            showError('Sign in failed. Please try again.');
            $('#submit-signin').button('reset');
        }else{
            window.location.href=response;
        }
    }
});
}

$('#submit-signin').click(function(){submitLoginForm()});

$('#login-form input').keypress(function(e){
      if(e.which == 13){
       submitLoginForm()
       }
      });    
", CClientScript::POS_READY);
$this->endWidget();
?>

<ul class="signin-divider"><li class="divider"></li></ul>
<a style="margin: 0px -20px;" href="<?php echo url('user/forgotpassword'); ?>">Forgot password?</a>

protected/views/user/admin.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List User','url'=>array('index')),
	array('label'=>'Create User','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('user-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Users</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'user_id',
		'email_address',
		'first_name',
		'last_name',
		'address',
		'phone_number',
		/*
		'password',
		'salt',
		'super_admin',
		'params',
		'last_login',
		'login_disabled',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

protected/views/user/forgot_password.php
<?php
$this->layout = '//layouts/aoHomeNarrow';
cs()->registerScript('autofocus', '
    $("#User_email_address").focus();
');
?>
<h1 class="title">Forgot Password</h1>
    <?php if ($model->isNewRecord) { ?>                    
        <div class="mid-header">Please provide your email address in the field below to reset your password.</div>
        <?php if ($emailSent) { ?>
            <?php cs()->registerScript('alert','(function(){ showError(\'We cannot find your user account. Please try again.\'); })();'); ?>
        <?php } ?>
        <?php
        $form = $this->beginWidget('ausa.widgets.AusaActiveForm', array(
            'id' => 'user-form',
            'htmlOptions' => array('class' => 'reset'),
            'enableAjaxValidation' => true,
        )); ?>
        <ul class="fields">
            <li>
                <i class="icon-envelope-alt"></i>    
                <?php echo $form->textField($model, 'email_address', array('autocomplete' => 'off', 'placeholder' => 'email address')); ?>
            </li>
        </ul>
        <div class="mid-form">
            <span class="login-checkbox pull-left">
                <?php echo CHtml::hiddenField('ajax', '0'); ?>
            </span>
            <?php
            $this->widget('bootstrap.widgets.TbButton', array(
                'buttonType' => 'submit',
                'label' => 'Reset Password',
                'type' => 'info',
                'htmlOptions' => array('class' => 'pull-right'),
                'block' => true,
                'size' => 'large',
            ));
            ?>
        </div>
        <?php
        $this->endWidget();
    } else {
        ?>
        <div class="inset-margin">
            <div class="mid-footer">
                Please check your email for instructions on resetting your account password. The email was sent to <code><?php echo $model->email_address; ?></code>.
            </div>
        </div>
<?php } ?>

protected/views/user/index.php
<?php
//This is INDEX page for Users View
$this->layout = '//layouts/full';
$breadcrumbs = array(
    'My Dashboard' => app()->user->getHomeUrl(),
    'Users',
);

$this->widget('application.components.widgets.AOUserHeaderBar', array('breadcrumbs' => $breadcrumbs));
?>

    <?php $this->beginWidget('application.components.widgets.AOPanel', array('multiCol' => false)); ?>
    <?php $this->beginWidget('application.components.widgets.AOPanelHead', array('panelIcon' => 'black-icons truck', 'panelTitle' => 'AUSA Users')); ?>
    <?php
    $this->widget('ausa.widgets.AOButtonGroup', array(
        'type' => '',
        'buttons' => array(
            array('icon' => 'cog', 'items' => array(
                    array('label' => 'Add a User', 'icon' => 'plus', 'url' => url('/user/create')),
                    '---',
                    array('label' => 'Get Help', 'icon' => 'question-sign', 'url' => '#'),
            )),
        ),
    ));
    ?>
    <?php $this->endWidget(); ?>
    <?php
    $dataArray = array(
        'type' => 'striped bordered condensed',
        'dataProvider' => $dataProvider,
        'columns' => array(
            array('name' => 'user_id', 'header' => 'ID'),
            array('name' => 'first_name', 'header' => 'First name', 'type' => 'raw', 'value' => 'CHtml::link($data->first_name,url("/user/update/" . $data->user_id))'),
            array('name' => 'last_name', 'header' => 'Last name'),
            array('name' => 'email_address', 'header' => 'Email'),
            array('name' => 'last_login', 'header' => 'Last Login'),
            ));
    
    if (app()->user->isAdmin()) {
        $dataArray["columns"][] = array(
            'class' => 'bootstrap.widgets.TbButtonColumn',
            'template' => '{update}',
        );
    }
    
    
    $this->widget('bootstrap.widgets.TbGridView', $dataArray);
    ?>

<?php $this->endWidget(); ?>

protected/views/user/login.php
<?php
$this->layout = '//layouts/aoHomeNarrow';
if($alert){ cs()->registerScript('alert','(function(){ showError(\'Sign in failed. Please try again.\'); })();'); }
?>
<h1 class="title">Sign In</h1>
<?php
    $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'user-form',
        'enableAjaxValidation' => true,
            )); ?>
    <ul class="fields">
        <li>
            <i class="icon-user" title="Email Address"></i>
            <?php echo $form->textField($model, 'username', array('autocomplete' => 'off', 'placeholder' => 'email address')); ?>
        </li>
        <li>
            <i class="icon-key" title="Password"></i>
            <?php echo $form->passwordField($model, 'password', array('autocomplete' => 'off', 'placeholder' => 'password')); ?>
        </li>
    </ul>
    <div class="mid-form">
        <span class="login-checkbox pull-left">
            <?php //echo $form->checkBoxRow($model, 'rememberMe'); ?>
        </span>
        <?php
        $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type' => 'success',
        'htmlOptions' => array('class' => 'pull-right'),
        'size' => 'large',
        'block' => true,
        'label' => 'Sign In',
        ));
        ?>
    </div>
    <div class="mid-footer">
        Forgot your password? Request a <a href="<?php echo url('/user/forgotpassword'); ?>">password reset</a>.
    </div>
<?php $this->endWidget(); ?>

protected/views/user/update.php
<?php

$this->layout = '//layouts/aoHomeNarrow';

$breadcrumbs = array(
    'My Dashboard' => app()->user->getHomeUrl(),
    'My Account',
);

if (app()->user->hasFlash('success')) {
    if (app()->user->hasFlash('emailChange')) {
        cs()->registerScript('email-changed', 'setTimeout(function() { alert(\'' . app()->user->getFlash('emailChange') . '\'); }, 500);');
    }
    cs()->registerScript('updates', 'setTimeout(function() { showSuccess(\'' . app()->user->getFlash('success') . '\'); }, 500);');
}

if ($model->hasErrors()) {
    cs()->registerScript('alert', 'showError(\'There are errors in your submission.\');');
}

cs()->registerScript('errors', '$("input.error").parent().css("background-color", "#f4cccc");');

echo $this->renderPartial('_form', array('model' => $model, 'vendor' => $vendor, 'chapter' => $chapter, 'st' => $st));

protected/views/user/verification_success.php
<?php
$this->layout = '//layouts/aoHomeHeader';

$this->beginWidget('bootstrap.widgets.TBHeroUnit', array(
    'heading' => 'Thank you'
))
?>
<p>
    Your email address <?php echo $model->email_address?> has been verified.
</p>

<?php
$this->endWidget();
?>